include: package:pedantic_mono/analysis_options.yaml

analyzer:
  exclude:
    - lib/**/*.gql.dart
    - lib/**/*.freezed.dart

  strong-mode:
    implicit-casts: false

  errors:
    unused_import: error

linter:
  rules: